version: '3.4'
services:
    ixia-mink:
        build: Php
        container_name: "ixia-mink"
        ports:
            - "80:80"
        volumes:
            - ../web/:/var/www/html/
        env_file:
            - variables.env
        depends_on:
            - ixia-mink-selenium-hub

    ixia-mink-selenium-hub:
        image: selenium/hub:3.11.0-dysprosium
        container_name: "ixia-mink-selenium-hub"
        ports:
            - "4444:4444"

    ixia-mink-chrome:
        #DEBUG VNC password: secret
#        image: selenium/node-chrome:3.11.0-dysprosium
        image: selenium/node-chrome-debug:3.11.0-dysprosium
        depends_on:
            - ixia-mink-selenium-hub
        ports:
            - "5900:5900"
        environment:
            - HUB_HOST=ixia-mink-selenium-hub
            - HUB_PORT=4444